# Copyright (C)2022 By ukyang. All Rights Reserved.
# Author: ukyang
# E-mail: ukyang_ma@163.com
# Date: 2022-06-07
# Description:

install:
	touch /usr/bin/see
	cp -f see.sh /usr/bin/see
	chmod +x /usr/bin/see
	touch /usr/bin/build
	cp -f build.sh /usr/bin/build
	chmod +x /usr/bin/build
	@echo "install successful."

uninstall:
	rm /usr/bin/see
	rm /usr/bin/build
	@echo "uninstall successful."
